THEME = faithful
MINIFY = min
BOOTSTRAP = bootstrap
SRC_LESS_DIR = ./less/
SRC_IMG_DIR = ./img/
SRC_JS_DIR =  ./js/
SRC_JS_EXT_DIR =  ./js/ext/
SRC_FONT_DIR = ./font/
DIST_DIR = ../${BOOTSTRAP}-${THEME}/
DIST_CSS_DIR = ${DIST_DIR}css/
DIST_IMG_DIR = ${DIST_DIR}img/
DIST_JS_DIR = ${DIST_DIR}js/
DIST_FONT_DIR = ${DIST_CSS_DIR}font/
DOCS_DIR = ./docs/assets/
DOCS_CSS_DIR = ${DOCS_DIR}css/
DOCS_IMG_DIR = ${DOCS_DIR}img/
DOCS_JS_DIR =  ${DOCS_DIR}js/
DOCS_FONT_DIR = ${DOCS_DIR}font/
BOOTSTRAP_CSS = ${BOOTSTRAP}.css
BOOTSTRAP_MIN = ${BOOTSTRAP}.${MINIFY}
BOOTSTRAP_MIN_CSS = ${BOOTSTRAP_MIN}.css
BOOTSTRAP_THEMED = ${BOOTSTRAP}-${THEME}
BOOTSTRAP_THEMED_CSS = ${BOOTSTRAP_THEMED}.css
BOOTSTRAP_THEMED_MIN_CSS = ${BOOTSTRAP_THEMED}.${MINIFY}.css
BOOTSTRAP_LESS = ${BOOTSTRAP}.less
BOOTSTRAP_RESPONSIVE = ${BOOTSTRAP}-responsive
BOOTSTRAP_RESPONSIVE_CSS = ${BOOTSTRAP_RESPONSIVE}.css
BOOTSTRAP_RESPONSIVE_MIN_CSS = ${BOOTSTRAP_RESPONSIVE}.${MINIFY}.css
BOOTSTRAP_RESPONSIVE_LESS = responsive.less
LIBERATION_FONT = liberation-font
LIBERATION_FONT_DIR = Liberation
LIBERATION_FONT_LESS = ${LIBERATION_FONT}.less
LIBERATION_FONT_CSS = ${LIBERATION_FONT}.css
LIBERATION_FONT_MIN_CSS = ${LIBERATION_FONT}.${MINIFY}.css
SOURCE_FONT = source-pro-font
SOURCE_FONT_DIR = Source
SOURCE_FONT_LESS = ${SOURCE_FONT}.less
SOURCE_FONT_CSS = ${SOURCE_FONT}.css
SOURCE_FONT_MIN_CSS = ${SOURCE_FONT}.${MINIFY}.css
FONTAWESOME_FONT = font-awesome
FONTAWESOME_FONT_IE7 = ${FONTAWESOME_FONT}-ie7
FONTAWESOME_FONT_DIR = FontAwesome
FONTAWESOME_FONT_LESS = ${FONTAWESOME_FONT}.less
FONTAWESOME_FONT_IE7_LESS = ${FONTAWESOME_FONT_IE7}.less
FONTAWESOME_FONT_CSS = ${FONTAWESOME_FONT}.css
FONTAWESOME_FONT_IE7_CSS = ${FONTAWESOME_FONT_IE7}.css
FONTAWESOME_FONT_MIN_CSS = ${FONTAWESOME_FONT}.${MINIFY}.css
FONTAWESOME_FONT_IE7_MIN_CSS = ${FONTAWESOME_FONT_IE7}.${MINIFY}.css
BOOTSTRAP_JS = ${BOOTSTRAP}.js
BOOTSTRAP_MIN_JS = ${BOOTSTRAP}.min.js
BOOTSWATCH = bootswatch
BOOTSWATCH_JS = ${BOOTSWATCH}.js
BOOTSWATCH_MIN_JS = ${BOOTSWATCH}.${MINIFY}.js
BOOTSWATCH_VER = 2.3.2
BOOTSWATCH_VER_JS = ${BOOTSWATCH}-${BOOTSWATCH_VER}.js
BOOTSWATCH_VER_MIN_JS = ${BOOTSWATCH}-${BOOTSWATCH_VER}.${MINIFY}.js
JQUERY = jquery
JQUERY_JS = ${JQUERY}.js
JQUERY_MIN_JS = ${JQUERY}.${MINIFY}.js
JQUERY_VER = 1.12.4
JQUERY_VER_JS = ${JQUERY}-${JQUERY_VER}.js
JQUERY_VER_MIN_JS = ${JQUERY}-${JQUERY_VER}.${MINIFY}.js
SMOOTH_SCROLL = jquery.smooth.scroll
SMOOTH_SCROLL_JS = ${SMOOTH_SCROLL}.js
SMOOTH_SCROLL_MIN_JS = ${SMOOTH_SCROLL}.${MINIFY}.js
SMOOTH_SCROLL_VER = 1.4.10
SMOOTH_SCROLL_VER_JS = ${SMOOTH_SCROLL}-${SMOOTH_SCROLL_VER}.js
SMOOTH_SCROLL_VER_MIN_JS = ${SMOOTH_SCROLL}-${SMOOTH_SCROLL_VER}.${MINIFY}.js
MODERNIZR = modernizr
MODERNIZR_JS = ${MODERNIZR}.js
MODERNIZR_MIN_JS = ${MODERNIZR}.${MINIFY}.js
MODERNIZR_VER = 2.8.3
MODERNIZR_VER_JS = ${MODERNIZR}-${MODERNIZR_VER}.js
MODERNIZR_VER_MIN_JS = ${MODERNIZR}-${MODERNIZR_VER}.${MINIFY}.js
RESPOND = respond
RESPOND_JS = ${RESPOND}.js
RESPOND_MIN_JS = ${RESPOND}.${MINIFY}.js
RESPOND_VER = 1.4.2
RESPOND_VER_JS = ${RESPOND}-${RESPOND_VER}.js
RESPOND_VER_MIN_JS = ${RESPOND}-${RESPOND_VER}.${MINIFY}.js
RESPOND_MATCHMEDIA = respond.matchmedia.addListener
RESPOND_MATCHMEDIA_JS = ${RESPOND_MATCHMEDIA}.js
RESPOND_MATCHMEDIA_MIN_JS = ${RESPOND_MATCHMEDIA}.${MINIFY}.js
RESPOND_MATCHMEDIA_VER = 1.4.2
RESPOND_MATCHMEDIA_VER_JS = ${RESPOND_MATCHMEDIA}-${RESPOND_MATCHMEDIA_VER}.js
RESPOND_MATCHMEDIA_VER_MIN_JS = ${RESPOND_MATCHMEDIA}-${RESPOND_MATCHMEDIA_VER}.${MINIFY}.js
HTML5SHIV = html5shiv
HTML5SHIV_JS = ${HTML5SHIV}.js
HTML5SHIV_MIN_JS = ${HTML5SHIV}.${MINIFY}.js
HTML5SHIV_VER = 3.7.3
HTML5SHIV_VER_JS = ${HTML5SHIV}-${HTML5SHIV_VER}.js
HTML5SHIV_VER_MIN_JS = ${HTML5SHIV}-${HTML5SHIV_VER}.${MINIFY}.js
HTML5SHIV_PRINTSHIV = html5shiv.printshiv
HTML5SHIV_PRINTSHIV_JS = ${HTML5SHIV_PRINTSHIV}.js
HTML5SHIV_PRINTSHIV_MIN_JS = ${HTML5SHIV_PRINTSHIV}.${MINIFY}.js
HTML5SHIV_PRINTSHIV_VER = 3.7.3
HTML5SHIV_PRINTSHIV_VER_JS = ${HTML5SHIV_PRINTSHIV}-${HTML5SHIV_PRINTSHIV_VER}.js
HTML5SHIV_PRINTSHIV_VER_MIN_JS = ${HTML5SHIV_PRINTSHIV}-${HTML5SHIV_PRINTSHIV_VER}.${MINIFY}.js
CSS3_MEDIAQUERIES = css3-mediaqueries
CSS3_MEDIAQUERIES_JS = ${CSS3_MEDIAQUERIES}.js
CSS3_MEDIAQUERIES_MIN_JS = ${CSS3_MEDIAQUERIES}.${MINIFY}.js


JSHINT = ./node_modules/.bin/jshint.cmd
UGLIFYJS = ./node_modules/.bin/uglifyjs.cmd
RECESS = ./node_modules/.bin/recess.cmd
LESSC = ./node_modules/.bin/lessc.cmd

DATE=$(shell date +%I:%M%p)
CHECK=√
HR=\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#


#
# BUILD DOCS
#

build:
	@echo "${HR}"
	@echo "   Building Bootstrap..."
	@echo "${HR}"
	@${JSHINT} ${SRC_JS_DIR}*.js --config ${SRC_JS_DIR}.jshintrc
	@${JSHINT} ${SRC_JS_DIR}tests/unit/*.js --config ${SRC_JS_DIR}.jshintrc
	@echo "Running JSHint on javascript...             ${CHECK} Done"
	@mkdir -p ${DIST_CSS_DIR}
	@echo "Compiling ${BOOTSTRAP_LESS}...               "
	@${RECESS} --compile ${SRC_LESS_DIR}${BOOTSTRAP_LESS} > ${DIST_CSS_DIR}${BOOTSTRAP_CSS}
	@${RECESS} --compress ${SRC_LESS_DIR}${BOOTSTRAP_LESS} > ${DIST_CSS_DIR}${BOOTSTRAP_MIN_CSS}	
	@echo "Compiling ${BOOTSTRAP_RESPONSIVE_LESS}...               "
	@${RECESS} --compile ${SRC_LESS_DIR}${BOOTSTRAP_RESPONSIVE_LESS} > ${DIST_CSS_DIR}${BOOTSTRAP_RESPONSIVE_CSS}
	@${RECESS} --compress ${SRC_LESS_DIR}${BOOTSTRAP_RESPONSIVE_LESS} > ${DIST_CSS_DIR}${BOOTSTRAP_RESPONSIVE_MIN_CSS}
	@echo "Compiling LESS with Recess...               ${CHECK} Done"	
	@echo "Compiling and minifying ${BOOTSTRAP_JS}...       "
	@mkdir -p ${DIST_JS_DIR}	
	@echo "/*!\n* Bootstrap.js v2.3.2 by @fat & @mdo\n* Copyright 2013 Twitter, Inc.\n* http://www.apache.org/licenses/LICENSE-2.0.txt\n*/" > ${DIST_JS_DIR}copyright.js	
	@cat ${SRC_JS_DIR}bootstrap-transition.js ${SRC_JS_DIR}bootstrap-alert.js ${SRC_JS_DIR}bootstrap-button.js ${SRC_JS_DIR}bootstrap-carousel.js ${SRC_JS_DIR}bootstrap-collapse.js ${SRC_JS_DIR}bootstrap-dropdown.js ${SRC_JS_DIR}bootstrap-modal.js ${SRC_JS_DIR}bootstrap-tooltip.js ${SRC_JS_DIR}bootstrap-popover.js ${SRC_JS_DIR}bootstrap-scrollspy.js ${SRC_JS_DIR}bootstrap-tab.js ${SRC_JS_DIR}bootstrap-typeahead.js ${SRC_JS_DIR}bootstrap-affix.js > ${DIST_JS_DIR}${BOOTSTRAP_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${BOOTSTRAP_JS} > ${DIST_JS_DIR}${BOOTSTRAP_MIN_JS}.tmp
	@cat ${DIST_JS_DIR}copyright.js ${DIST_JS_DIR}${BOOTSTRAP_MIN_JS}.tmp > ${DIST_JS_DIR}${BOOTSTRAP_MIN_JS}
	@rm ${DIST_JS_DIR}copyright.js ${DIST_JS_DIR}${BOOTSTRAP_MIN_JS}.tmp
	@echo "Compiling and minifying ${BOOTSWATCH_VER_JS}...       "
	@cp ${SRC_JS_EXT_DIR}${BOOTSWATCH_VER_JS} ${DIST_JS_DIR}${BOOTSWATCH_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${BOOTSWATCH_JS} > ${DIST_JS_DIR}${BOOTSWATCH_MIN_JS}
	@echo "Compiling and minifying ${JQUERY_VER_JS}...       "
	@cp ${SRC_JS_EXT_DIR}${JQUERY_VER_JS} ${DIST_JS_DIR}${JQUERY_JS}	
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${JQUERY_JS} > ${DIST_JS_DIR}${JQUERY_MIN_JS}
	@echo "Compiling and minifying ${SMOOTH_SCROLL_VER_JS}...       "
	@cp ${SRC_JS_EXT_DIR}${SMOOTH_SCROLL_VER_JS} ${DIST_JS_DIR}${SMOOTH_SCROLL_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${SMOOTH_SCROLL_JS} > ${DIST_JS_DIR}${SMOOTH_SCROLL_MIN_JS}
	@echo "Compiling and minifying ${CSS3_MEDIAQUERIES_JS}...       "
	@cp ${SRC_JS_EXT_DIR}${CSS3_MEDIAQUERIES_JS} ${DIST_JS_DIR}${CSS3_MEDIAQUERIES_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${CSS3_MEDIAQUERIES_JS} > ${DIST_JS_DIR}${CSS3_MEDIAQUERIES_MIN_JS}	
	@echo "Compiling and minifying ${HTML5SHIV_VER_JS}...       "
	@cp ${SRC_JS_EXT_DIR}${HTML5SHIV_VER_JS} ${DIST_JS_DIR}${HTML5SHIV_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${HTML5SHIV_JS} > ${DIST_JS_DIR}${HTML5SHIV_MIN_JS}
	@cp ${SRC_JS_EXT_DIR}${HTML5SHIV_PRINTSHIV_VER_JS} ${DIST_JS_DIR}${HTML5SHIV_PRINTSHIV_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${HTML5SHIV_PRINTSHIV_JS} > ${DIST_JS_DIR}${HTML5SHIV_PRINTSHIV_MIN_JS}			
	@echo "Compiling and minifying ${MODERNIZR_VER_JS}...       "
	@cp ${SRC_JS_EXT_DIR}${MODERNIZR_VER_JS} ${DIST_JS_DIR}${MODERNIZR_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${MODERNIZR_JS} > ${DIST_JS_DIR}${MODERNIZR_MIN_JS}	
	@echo "Compiling and minifying ${RESPOND_VER_JS}...       "
	@cp ${SRC_JS_EXT_DIR}${RESPOND_VER_JS} ${DIST_JS_DIR}${RESPOND_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${RESPOND_JS} > ${DIST_JS_DIR}${RESPOND_MIN_JS}
	@cp ${SRC_JS_EXT_DIR}${RESPOND_MATCHMEDIA_VER_JS} ${DIST_JS_DIR}${RESPOND_MATCHMEDIA_JS}
	@${UGLIFYJS} -nc ${DIST_JS_DIR}${RESPOND_MATCHMEDIA_JS} > ${DIST_JS_DIR}${RESPOND_MATCHMEDIA_MIN_JS}	
	@echo "Compiling and minifying javascript...       ${CHECK} Done"
	@mkdir -p ${DIST_IMG_DIR}
	@cp ${SRC_IMG_DIR}* ${DIST_IMG_DIR}
	@echo "Copying glyphicons and images...       	    ${CHECK} Done"
	@mkdir -p ${DIST_FONT_DIR}
	@echo "Copying Font-Awesome font...  "	
	@${LESSC} --compile ${SRC_LESS_DIR}${FONTAWESOME_FONT_LESS} > ${DIST_CSS_DIR}${FONTAWESOME_FONT_CSS}
	@${LESSC} --compress ${SRC_LESS_DIR}${FONTAWESOME_FONT_LESS} > ${DIST_CSS_DIR}${FONTAWESOME_FONT_MIN_CSS}
	@${LESSC} --compile ${SRC_LESS_DIR}${FONTAWESOME_FONT_IE7_LESS} > ${DIST_CSS_DIR}${FONTAWESOME_FONT_IE7_CSS}
	@${LESSC} --compress ${SRC_LESS_DIR}${FONTAWESOME_FONT_IE7_LESS} > ${DIST_CSS_DIR}${FONTAWESOME_FONT_IE7_MIN_CSS}
	@cp -R ${SRC_FONT_DIR}${FONTAWESOME_FONT_DIR} ${DIST_FONT_DIR}${FONTAWESOME_FONT_DIR}
	@echo "Copying Liberation font...  "
	@${LESSC} --compile ${SRC_LESS_DIR}${LIBERATION_FONT_LESS} > ${DIST_CSS_DIR}${LIBERATION_FONT_CSS}
	@${LESSC} --compress ${SRC_LESS_DIR}${LIBERATION_FONT_LESS} > ${DIST_CSS_DIR}${LIBERATION_FONT_MIN_CSS}	
	@cp -R ${SRC_FONT_DIR}${LIBERATION_FONT_DIR} ${DIST_FONT_DIR}${LIBERATION_FONT_DIR}
	@echo "Copying Source font...  "
	@${LESSC} --compile ${SRC_LESS_DIR}${SOURCE_FONT_LESS} > ${DIST_CSS_DIR}${SOURCE_FONT_CSS}
	@${LESSC} --compress ${SRC_LESS_DIR}${SOURCE_FONT_LESS} > ${DIST_CSS_DIR}${SOURCE_FONT_MIN_CSS}	
	@cp -R ${SRC_FONT_DIR}${SOURCE_FONT_DIR} ${DIST_FONT_DIR}${SOURCE_FONT_DIR}
	@echo "Copying 3rdparty font...  ${CHECK} Done"
	@node docs/build
	@mkdir -p ${DOCS_CSS_DIR}
	@cp ${DIST_CSS_DIR}*.css ${DOCS_CSS_DIR}
	@mkdir -p ${DOCS_JS_DIR}
	@cp ${DIST_JS_DIR}*.js ${DOCS_JS_DIR}
	@mkdir -p ${DOCS_IMG_DIR}
	@cp ${DIST_IMG_DIR}* ${DOCS_IMG_DIR}
	@mkdir -p ${DOCS_FONT_DIR}
	@cp -R ${DIST_FONT_DIR} ${DOCS_FONT_DIR}
	@echo "Compiling documentation...                  ${CHECK} Done"
	@echo "${HR}"
	@echo "   Bootstrap successfully built at ${DATE}."
	@echo "   Thanks for using Bootstrap, <3 @mdo and @fat"
	@echo "${HR}"

#
# RUN JSHINT & QUNIT TESTS IN PHANTOMJS
#

test:
	./node_modules/.bin/jshint js/*.js --config js/.jshintrc
	./node_modules/.bin/jshint js/tests/unit/*.js --config js/.jshintrc
	node js/tests/server.js &
	phantomjs js/tests/phantom.js "http://localhost:3000/js/tests"
	kill -9 `cat js/tests/pid.txt`
	rm js/tests/pid.txt

#
# CLEANS THE ROOT DIRECTORY OF PRIOR BUILDS
#

clean:	
	rm -r ${DIST_DIR}

#
# BUILD SIMPLE BOOTSTRAP DIRECTORY
# recess & uglifyjs are required
#

bootstrap: bootstrap-img bootstrap-css bootstrap-js


#
# JS COMPILE
#
bootstrap-js: bootstrap/js/*.js

bootstrap/js/*.js: js/*.js
	mkdir -p bootstrap/js
	cat js/bootstrap-transition.js js/bootstrap-alert.js js/bootstrap-button.js js/bootstrap-carousel.js js/bootstrap-collapse.js js/bootstrap-dropdown.js js/bootstrap-modal.js js/bootstrap-tooltip.js js/bootstrap-popover.js js/bootstrap-scrollspy.js js/bootstrap-tab.js js/bootstrap-typeahead.js js/bootstrap-affix.js > bootstrap/js/bootstrap.js
	./node_modules/.bin/uglifyjs -nc bootstrap/js/bootstrap.js > bootstrap/js/bootstrap.min.tmp.js
	echo "/*!\n* Bootstrap.js by @fat & @mdo\n* Copyright 2013 Twitter, Inc.\n* http://www.apache.org/licenses/LICENSE-2.0.txt\n*/" > bootstrap/js/copyright.js
	cat bootstrap/js/copyright.js bootstrap/js/bootstrap.min.tmp.js > bootstrap/js/bootstrap.min.js
	rm bootstrap/js/copyright.js bootstrap/js/bootstrap.min.tmp.js

#
# CSS COMPLILE
#

bootstrap-css: bootstrap/css/*.css

bootstrap/css/*.css: less/*.less
	mkdir -p bootstrap/css
	./node_modules/.bin/recess --compile ${BOOTSTRAP_LESS} > bootstrap/css/bootstrap.css
	./node_modules/.bin/recess --compress ${BOOTSTRAP_LESS} > bootstrap/css/bootstrap.min.css
	./node_modules/.bin/recess --compile ${BOOTSTRAP_RESPONSIVE_LESS} > bootstrap/css/bootstrap-responsive.css
	./node_modules/.bin/recess --compress ${BOOTSTRAP_RESPONSIVE_LESS} > bootstrap/css/bootstrap-responsive.min.css

#
# IMAGES
#

bootstrap-img: bootstrap/img/*

bootstrap/img/*: img/*
	mkdir -p bootstrap/img
	cp img/* bootstrap/img/


#
# MAKE FOR GH-PAGES 4 FAT & MDO ONLY (O_O  )
#

gh-pages: bootstrap docs
	rm -f docs/assets/bootstrap.zip
	zip -r docs/assets/bootstrap.zip bootstrap
	rm -r bootstrap
	rm -f ../bootstrap-gh-pages/assets/bootstrap.zip
	node docs/build production
	cp -r docs/* ../bootstrap-gh-pages

#
# WATCH LESS FILES
#

watch:
	echo "Watching less files..."; \
	watchr -e "watch('less/.*\.less') { system 'make' }"


.PHONY: docs watch gh-pages bootstrap-img bootstrap-css bootstrap-js